CREATE 
--ALTER
PROC USP_XEMNHA1
	@MaNha INT
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT * FROM NHA WHERE MaNha = @MaNha)
				BEGIN
					PRINT @MaNha + N'NHÀ KHÔNG TỒN TẠI'
					ROLLBACK TRAN
					RETURN 1
				END
			SELECT * FROM NHA WHERE MaNha = @MaNha
		END TRY
		BEGIN CATCH
			PRINT N' LỖI HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END CATCH
	IF @@TRANCOUNT > 0 
	COMMIT TRAN
	RETURN 0
END
GO