CREATE 
--ALTER
PROC USP_CAPNHATTENDUONG
	@MaNHa INT,
	@Duong NVARCHAR(50)
AS 
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT * FROM NHA WHERE MaNha = @MaNHa)
			BEGIN
				PRINT @MaNHa + N'NHÀ KHÔNG TỒN TẠI'
				ROLLBACK TRAN
				RETURN 1
			END
			IF (@Duong IS NULL OR @Duong = '')
			BEGIN
				PRINT @Duong + N' KHÔNG ĐƯỢC ĐỂ TRỐNG(NULL)'
				ROLLBACK TRAN
				RETURN 1
			END
			UPDATE NHA
			SET Duong = @Duong
			WHERE MaNha = @MaNha

			--ĐỂ TEST
			WAITFOR DELAY '0:0:05'
			DECLARE @RT INT
			SELECT @RT = COUNT(*) FROM NHA
			WHERE Duong = @Duong
			IF @RT >= 2
			BEGIN
				ROLLBACK TRAN
				RETURN 1
			END
			PRINT N' CẬP NHẬT THÀNH CÔNG'
		END TRY
		BEGIN CATCH
			PRINT N' LỖI HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END CATCH
	IF @@TRANCOUNT > 0
	COMMIT TRAN
	RETURN 0
END
GO