CREATE PROC sp_XemChuNha
@MaChuNha NVARCHAR(50),
@TenChuNha NVARCHAR(50)
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
BEGIN TRY
IF NOT EXISTS (SELECT * FROM CHUNHA WHERE CHUNHA.MaChuNha = @MaChuNha)
BEGIN
PRINT N'LỖI MaChuNha KHÔNG TỒN TẠI'
ROLLBACK TRAN
RETURN 1; -- Lỗi do dữ liệu CSDL
END
IF @MaChuNha IS NULL
BEGIN
PRINT N'LỖI MaChuNha KHÔNG TỒN TẠI'
ROLLBACK TRAN
RETURN 2; -- Lỗi do dữ liệu input
END
DECLARE @Count INT = 0;
SELECT @Count = COUNT(*)
FROM CHUNHA
WHERE @TenChuNha LIKE N'Nguyễn%';
PRINT 'Số lượng chủ nhà có họ Nguyễn: ' + CAST(@Count AS NVARCHAR(10));
SELECT * FROM CHUNHA
WHERE MaChuNha = @MaChuNha AND  WHERE @TenChuNha LIKE N'Nguyễn%';
PRINT 'Số lượng chủ nhà có họ Nguyễn: ' + CAST(@Count AS NVARCHAR(10));
END TRY
BEGIN CATCH
PRINT N'LỖI HỆ THỐNG'
ROLLBACK TRAN
END CATCH
COMMIT TRAN

GO
---------------------------------------------
CREATE PROC sp_XemDanhSachNha
@TenChuNha NVARCHAR(50),
@DiaChi NVARCHAR(50),
@SDT INT
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
BEGIN TRY
INSERT CHUNHA(TenChuNha, DiaChi, SDT) VALUE (@TenChuNha, @DiaChi, @SDT)
END TRY
BEGIN CATCH
PRINT N'LỖI HỆ THỐNG'
ROLLBACK TRAN
END CATCH
COMMIT TRAN