CREATE 
--ALTER
PROC USP_XOACHUNHA1
	@MaChuNha INT
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT * FROM CHUNHA WHERE MaChuNha = @MaChuNha)
				BEGIN
					PRINT N'CHỦ NHÀ KHÔNG TỒN TẠI'
					ROLLBACK TRAN
					RETURN 1
				END
			DELETE FROM CHUNHA WHERE MaChuNha = @MaChuNha
		END TRY
		BEGIN CATCH
			PRINT N' LỖI HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END CATCH
	IF @@TRANCOUNT > 0 
	COMMIT TRAN
	RETURN 0
END
GO