CREATE 
--ALTER
PROC USP_XEMCHUNHA1
	@Quan NVARCHAR(50)
AS 
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT * FROM CHUNHA WHERE DiaChi LIKE N'%' + @QUAN + '%')
				BEGIN
					PRINT N'CHỦ NHÀ KHÔNG TỒN TẠI'
					ROLLBACK TRAN
					RETURN 1
				END
			IF (@Quan IS NULL OR @Quan = '')
			BEGIN
				PRINT @Quan + N' KHÔNG ĐƯỢC ĐỂ TRỐNG(NULL)'
				ROLLBACK TRAN
				RETURN 1
			END

			DECLARE @TONG INT
			SET @TONG = (SELECT COUNT(*) FROM CHUNHA
			WHERE DiaChi LIKE N'%' + @QUAN + '%')
			BEGIN
				PRINT @Quan + N' CÓ ' + CAST(@TONG AS NVARCHAR(20)) + N' CHỦ NHÀ'
			END
			--ĐỂ TEST
			WAITFOR DELAY '0:0:05'			SELECT * FROM CHUNHA 
			WHERE DiaChi LIKE N'%' + @QUAN + '%'

		END TRY
		BEGIN CATCH
			PRINT N' LỖI HỆ THỐNG'
			ROLLBACK TRAN
			RETURN 1
		END CATCH
	IF @@TRANCOUNT > 0
	COMMIT TRAN
	RETURN 0
END
GO