CREATE PROC sp_CapNhatDieuKienCN
@MaNha NVARCHAR(50),
@DieuKienCN NVARCHAR(50)
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
BEGIN TRY
IF NOT EXISTS (SELECT * FROM NHA WHERE NHA.MaNha = @MaNha)
BEGIN
PRINT N'LỖI MaNha KHÔNG TỒN TẠI'
ROLLBACK TRAN
RETURN 1; -- Lỗi do dữ liệu CSDL
END
IF @MaNha IS NULL
BEGIN
PRINT N'LỖI MaNha KHÔNG TỒN TẠI'
ROLLBACK TRAN
RETURN 2; -- Lỗi do dữ liệu input
END
BEGIN TRY
UPDATE NHA
SET DieuKienCN = @DieuKienCN
WHERE MaNha = @MaNha
END TRY
BEGIN CATCH
PRINT N'LỖI HỆ THỐNG'
ROLLBACK TRAN
END CATCH
COMMIT TRAN

GO
---------------------------------------------
CREATE PROC sp_XemDanhSachNha
@MaNha NVARCHAR(50),
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
BEGIN TRY
IF NOT EXISTS (SELECT * FROM NHA WHERE NHA.MaNha = @MaNha)
BEGIN
PRINT N'LỖI MaNha KHÔNG TỒN TẠI'
ROLLBACK TRAN
RETURN 1; -- Lỗi do dữ liệu CSDL
END
SELECT *
FROM NHA
WHERE MaNha = @MaNha
END TRY
BEGIN CATCH
PRINT N'LỖI HỆ THỐNG'
ROLLBACK TRAN
END CATCH
COMMIT TRAN